# Tensors

In [1]:
import torch
# Print the PyTorch version to ensure it's installed and functioning correctly.
print(torch.__version__)

2.9.0+cu126


In [2]:
# Check if a CUDA-enabled GPU is available for computations.
# If available, it prints the name of the first CUDA device.
if torch.cuda.is_available():
    print("cuda is available",torch.cuda.get_device_name(0))
else:
    print("cuda is not available")

cuda is available Tesla T4


#  Creating tesnsors

In [3]:
# Create an empty tensor of shape (2, 3).
# The values are uninitialized and will contain arbitrary memory content.
a=torch.empty(2,3)
a

tensor([[0.0000e+00, 2.2421e-44, 0.0000e+00],
        [7.0079e-39, 0.0000e+00, 0.0000e+00]])

In [4]:
# Check the data type of the tensor 'a'.
# By default, PyTorch creates float32 tensors.
type(a)

torch.Tensor

In [5]:
# Create a tensor of shape (2, 3) filled with zeros.
b=torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# Create a tensor of shape (2, 3) filled with ones.
c=torch.ones(2,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# Create a tensor of shape (2, 3) with random values uniformly sampled from [0, 1).
d=torch.rand(2,3)
d

tensor([[0.1809, 0.8569, 0.9660],
        [0.3295, 0.0416, 0.7860]])

In [8]:
# Set the random seed for reproducibility.
# This ensures that subsequent random tensor creations will produce the same sequence of numbers.
torch.manual_seed(100)
e=torch.rand(2,3)
e

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# Set the random seed again to demonstrate reproducibility.
# 'f' will have the same random values as 'e' because the seed is reset.
torch.manual_seed(100)
f=torch.rand(2,3)
f

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# Create a tensor directly from a Python list or NumPy array.
g=torch.tensor([[1,2,3],[4,5,6]])
g

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# Other ways to create tensors:

# Using torch.arange: Creates a 1D tensor with values from 1 to 10 (exclusive) with a step of 2.
h=torch.arange(1,10,2)
print(h)

# Using torch.linspace: Creates a 1D tensor with 5 evenly spaced points between 1 and 10 (inclusive).
i=torch.linspace(1,10,steps=5)
print(i)

# Using torch.eye: Creates a 5x5 identity matrix.
j=torch.eye(5)
print(j)

# Using torch.full: Creates a tensor of shape (2, 3) filled with the specified value (4).
k=torch.full((2,3),4)
print(k)

tensor([1, 3, 5, 7, 9])
tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[4, 4, 4],
        [4, 4, 4]])


## Tensor Shape

In [12]:
# Get the shape (dimensions) of tensor 'j'.
# `shape` returns a torch.Size object, which is a tuple-like object.
j.shape

torch.Size([5, 5])

In [13]:
# Create an empty tensor with the same shape as an existing tensor 'j'.
# The values are uninitialized.
t=torch.empty_like(j)
t

tensor([[8.2428e-03, 0.0000e+00, 8.0700e-03, 0.0000e+00, 1.1210e-43],
        [0.0000e+00, 8.9683e-44, 0.0000e+00, 8.1105e-03, 0.0000e+00],
        [0.0000e+00, 1.5046e-36, 1.7371e-06, 0.0000e+00, 1.0842e-19],
        [0.0000e+00, 8.0457e-03, 0.0000e+00, 8.0251e-03, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.3593e-43, 0.0000e+00, 8.0472e-03]])

In [14]:
# Create a tensor filled with ones, using the same shape as tensor 'j'.
q=torch.ones_like(j)
q

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [15]:
# Create a tensor with random values, using the same shape as tensor 'j'.
w=torch.rand_like(j)
w

tensor([[0.2627, 0.0428, 0.2080, 0.1180, 0.1217],
        [0.7356, 0.7118, 0.7876, 0.4183, 0.9014],
        [0.9969, 0.7565, 0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770, 0.4440, 0.9478],
        [0.7445, 0.4892, 0.2426, 0.7003, 0.5277]])

In [16]:
# Create a tensor filled with zeros, using the same shape as tensor 'k'.
e=torch.zeros_like(k)
k

tensor([[4, 4, 4],
        [4, 4, 4]])

## Tensor Datatype

In [17]:
# Find the data type of tensor 'w'.
# Common data types include torch.float32, torch.float64, torch.int32, torch.int64, etc.
w.dtype

torch.float32

In [18]:
# Create a tensor and explicitly assign its data type to float32.
torch.tensor([[1,2,4,5],[1,2,34,5]],dtype=torch.float32)

tensor([[ 1.,  2.,  4.,  5.],
        [ 1.,  2., 34.,  5.]])

In [19]:
# Create a tensor and explicitly assign its data type to int32.
torch.tensor([[1,2,4,5],[1,2,34,5]],dtype=torch.int32)

tensor([[ 1,  2,  4,  5],
        [ 1,  2, 34,  5]], dtype=torch.int32)

In [20]:
# Convert tensor 't' to a new tensor with data type int32.
# The original tensor 't' remains unchanged.
t.to(torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

## Mathematical operatons

### 1.Scaler Operations


In [21]:
# Create a 2x4 tensor with random values for demonstrating scalar operations.
x=torch.rand(2,4)
x

tensor([[0.2472, 0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064, 0.1629]])

In [22]:
# Scalar addition: Add 1 to every element of tensor x.
print(x + 1)

# Scalar subtraction: Subtract 1 from every element of tensor x.
print(x - 1)

# Scalar multiplication: Multiply every element of tensor x by 2.
print(x * 2)

# Scalar division: Divide every element of tensor x by 2.
print(x / 2)

# Integer division: Multiply by 100 then integer divide by 2.
print((x * 100) // 2)

# Modulo: Compute the remainder of each element when divided by 2.
print(x % 2)

# Power: Raise each element of tensor x to the power of 5.
print(x ** 5)

tensor([[1.2472, 1.7909, 1.4235, 1.0169],
        [1.2209, 1.9535, 1.7064, 1.1629]])
tensor([[-0.7528, -0.2091, -0.5765, -0.9831],
        [-0.7791, -0.0465, -0.2936, -0.8371]])
tensor([[0.4944, 1.5818, 0.8470, 0.0338],
        [0.4418, 1.9071, 1.4128, 0.3258]])
tensor([[0.1236, 0.3954, 0.2117, 0.0084],
        [0.1104, 0.4768, 0.3532, 0.0814]])
tensor([[12., 39., 21.,  0.],
        [11., 47., 35.,  8.]])
tensor([[0.2472, 0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064, 0.1629]])
tensor([[9.2278e-04, 3.0944e-01, 1.3621e-02, 1.3782e-09],
        [5.2593e-04, 7.8829e-01, 1.7590e-01, 1.1463e-04]])


### 2.Elementwies operation

In [23]:
# Create two random 2x3 tensors for demonstrating element-wise operations.
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182]])
tensor([[0.5261, 0.0447, 0.5123],
        [0.9051, 0.5989, 0.4450]])


In [24]:

# Element-wise addition of tensors a and b.
print("a + b:\n", a + b)

# Element-wise subtraction of tensors a and b.
print("a - b:\n", a - b)

# Element-wise multiplication of tensors a and b.
print("a * b:\n", a * b)

# Element-wise division of tensors a and b.
print("a / b:\n", a / b)

# Element-wise power: Raise elements of a to the power of corresponding elements in b.
print("a ** b:\n", a ** b)

# Element-wise maximum: Returns a new tensor with the maximum of each pair of elements from a and b.
print("max(a, b):\n", torch.max(a, b))

# Element-wise minimum: Returns a new tensor with the minimum of each pair of elements from a and b.
print("min(a, b):\n", torch.min(a, b))

a + b:
 tensor([[1.4163, 0.5609, 0.5482],
        [1.5527, 0.9419, 0.7632]])
a - b:
 tensor([[ 0.3641,  0.4716, -0.4765],
        [-0.2574, -0.2558, -0.1268]])
a * b:
 tensor([[0.4683, 0.0231, 0.0184],
        [0.5862, 0.2054, 0.1416]])
a / b:
 tensor([[ 1.6921, 11.5604,  0.0700],
        [ 0.7156,  0.5728,  0.7151]])
a ** b:
 tensor([[0.9406, 0.9709, 0.1818],
        [0.6749, 0.5269, 0.6008]])
max(a, b):
 tensor([[0.8902, 0.5163, 0.5123],
        [0.9051, 0.5989, 0.4450]])
min(a, b):
 tensor([[0.5261, 0.0447, 0.0359],
        [0.6476, 0.3430, 0.3182]])


In [25]:
print("abs(a):\n", torch.abs(a))        # absolute value of each element
print("ceil(a):\n", torch.ceil(a))      # round up each element to the smallest integer greater than or equal to it
print("floor(a):\n", torch.floor(a))    # round down each element to the largest integer less than or equal to it
print("round(a):\n", torch.round(a))    # round each element to the nearest integer

print("sqrt(a.abs()):\n", torch.sqrt(torch.abs(a)))  # square root of the absolute value of each element
print("exp(a):\n", torch.exp(a))        # exponential of each element (e^x)
print("log(abs(a)+1):\n", torch.log(torch.abs(a) + 1))  # natural logarithm of (absolute value of each element + 1)

print("sin(a):\n", torch.sin(a))        # sine of each element
print("cos(a):\n", torch.cos(a))        # cosine of each element
print("tan(a):\n", torch.tan(a))        # tangent of each element

print("clamp(a, -1, 1):\n", torch.clamp(a, 2, 3))  # element-wise clipping: values below 2 become 2, values above 3 become 3

abs(a):
 tensor([[0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182]])
ceil(a):
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
floor(a):
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
round(a):
 tensor([[1., 1., 0.],
        [1., 0., 0.]])
sqrt(a.abs()):
 tensor([[0.9435, 0.7185, 0.1894],
        [0.8048, 0.5857, 0.5641]])
exp(a):
 tensor([[2.4356, 1.6758, 1.0365],
        [1.9110, 1.4092, 1.3747]])
log(abs(a)+1):
 tensor([[0.6367, 0.4163, 0.0353],
        [0.4993, 0.2949, 0.2763]])
sin(a):
 tensor([[0.7772, 0.4936, 0.0359],
        [0.6033, 0.3363, 0.3129]])
cos(a):
 tensor([[0.6293, 0.8697, 0.9994],
        [0.7975, 0.9417, 0.9498]])
tan(a):
 tensor([[1.2351, 0.5676, 0.0359],
        [0.7565, 0.3571, 0.3294]])
clamp(a, -1, 1):
 tensor([[2., 2., 2.],
        [2., 2., 2.]])


### 3.Reducation operations

In [26]:
import torch

# Create a random integer tensor of shape (2,3) with values between 0 and 9, and cast to float32.
e = torch.randint(low=0, high=10, size=(2,3),dtype=torch.float32)
print("e:\n", e)

e:
 tensor([[9., 2., 6.],
        [7., 7., 8.]])


In [27]:

# Calculate the sum of all elements in tensor 'e'.
print("\nsum:\n", torch.sum(e))
# Calculate the sum of elements along dimension 0 (columns).
print("\nsum(dim=0):\n", torch.sum(e, dim=0))
# Calculate the sum of elements along dimension 1 (rows).
print("\nsum(dim=1):\n", torch.sum(e, dim=1))


sum:
 tensor(39.)

sum(dim=0):
 tensor([16.,  9., 14.])

sum(dim=1):
 tensor([17., 22.])


In [28]:
# ----- MEAN -----
# Calculate the mean of all elements in tensor 'e'. Must cast to float for mean.
print("\nmean:\n", torch.mean(e.float()))


# ----- PRODUCT -----
# Calculate the product of all elements in tensor 'e'.
print("\nproduct:\n", torch.prod(e))


# ----- MAX -----
# Find the maximum value in tensor 'e'.
print("\nmax:\n", torch.max(e))


# ----- MIN -----
# Find the minimum value in tensor 'e'.
print("\nmin:\n", torch.min(e))


mean:
 tensor(6.5000)

product:
 tensor(42336.)

max:
 tensor(9.)

min:
 tensor(2.)


In [29]:


# ----- ARGMAX -----
# Find the index of the maximum value in the flattened tensor 'e'.
print("\nargmax (flattened index):\n", torch.argmax(e))


# ----- ARGMIN -----
# Find the index of the minimum value in the flattened tensor 'e'.
print("\nargmin (flattened index):\n", torch.argmin(e))


# ----- SUM ALONG DIMENSIONS -----
# Calculate the sum of elements along dimension 0 (columns).
print("\nsum(dim=0):\n", torch.sum(e, dim=0))
# Calculate the sum of elements along dimension 1 (rows).
print("sum(dim=1):\n", torch.sum(e, dim=1))


# ----- MEAN ALONG DIMENSIONS -----
# Calculate the mean of elements along dimension 0 (columns), cast to float.
print("\nmean(dim=0):\n", torch.mean(e.float(), dim=0))
# Calculate the mean of elements along dimension 1 (rows), cast to float.
print("mean(dim=1):\n", torch.mean(e.float(), dim=1))


argmax (flattened index):
 tensor(0)

argmin (flattened index):
 tensor(1)

sum(dim=0):
 tensor([16.,  9., 14.])
sum(dim=1):
 tensor([17., 22.])

mean(dim=0):
 tensor([8.0000, 4.5000, 7.0000])
mean(dim=1):
 tensor([5.6667, 7.3333])


In [30]:


# ----- STANDARD DEVIATION -----
# Calculate the standard deviation of all elements in tensor 'e'.
print("\nstd:\n", torch.std(e.float()))


# ----- VARIANCE -----
# Calculate the variance of all elements in tensor 'e'.
print("\nvar:\n", torch.var(e.float()))


# ----- ANY / ALL (logical reductions) -----
# Check if any element in 'e' is greater than 5.
print("\nany > 5:\n", torch.any(e > 5))
# Check if all elements in 'e' are greater than 0.
print("all > 0:\n", torch.all(e > 0))


# ----- L1 & L2 NORM -----
# Calculate the L2 (Euclidean) norm of tensor 'e'.
print("\nL2 norm:\n", torch.norm(e.float()))
# Calculate the L1 (Manhattan) norm of tensor 'e'.
print("L1 norm:\n", torch.norm(e.float(), p=1))


# ----- MEDIAN -----
# Calculate the median of all elements in tensor 'e'.
print("\nmedian:\n", torch.median(e.float()))


std:
 tensor(2.4290)

var:
 tensor(5.9000)

any > 5:
 tensor(True)
all > 0:
 tensor(True)

L2 norm:
 tensor(16.8226)
L1 norm:
 tensor(39.)

median:
 tensor(7.)


### 4.Metrix Operation

In [31]:
A = torch.randint(0, 10, (3, 3)).float() # Create a 3x3 matrix with random integers (0-9) as floats.
B = torch.randint(0, 10, (3, 3)).float() # Create another 3x3 matrix with random integers (0-9) as floats.

print("A:\n", A)
print("B:\n", B)

A:
 tensor([[3., 6., 1.],
        [5., 5., 0.],
        [4., 3., 8.]])
B:
 tensor([[8., 3., 3.],
        [5., 0., 6.],
        [4., 0., 8.]])


In [32]:

# ----- MATRIX ADDITION -----
# Element-wise addition of matrices A and B.
print("\nA + B:\n", A + B)


# ----- MATRIX SUBTRACTION -----
# Element-wise subtraction of matrices A and B.
print("\nA - B:\n", A - B)



A + B:
 tensor([[11.,  9.,  4.],
        [10.,  5.,  6.],
        [ 8.,  3., 16.]])

A - B:
 tensor([[-5.,  3., -2.],
        [ 0.,  5., -6.],
        [ 0.,  3.,  0.]])


In [33]:

# ----- MATRIX MULTIPLICATION (element-wise) -----
# Performs element-wise multiplication (Hadamard product).
print("\nA * B (element-wise):\n", A * B)


# ----- MATRIX MULTIPLICATION (true matmul) -----
# Performs true matrix multiplication (dot product of rows and columns).
print("\nA @ B (matrix multiply):\n", A @ B)


# ----- MATRIX MULTIPLY using torch.matmul -----
# Another way to perform true matrix multiplication.
print("\ntorch.matmul(A, B):\n", torch.matmul(A, B))



A * B (element-wise):
 tensor([[24., 18.,  3.],
        [25.,  0.,  0.],
        [16.,  0., 64.]])

A @ B (matrix multiply):
 tensor([[58.,  9., 53.],
        [65., 15., 45.],
        [79., 12., 94.]])

torch.matmul(A, B):
 tensor([[58.,  9., 53.],
        [65., 15., 45.],
        [79., 12., 94.]])


In [34]:
# ----- DOT PRODUCT (vectors only) -----
v1 = torch.tensor([1., 2., 3.]) # Create a 1D tensor (vector).
v2 = torch.tensor([4., 5., 6.]) # Create another 1D tensor (vector).
print("\ndot product v1·v2:\n", torch.dot(v1, v2))


# ----- MATRIX TRANSPOSE -----
# Transposes matrix A (swaps rows and columns).
print("\nA transpose (A.T):\n", A.T)


# ----- MATRIX INVERSE -----
# Computes the inverse of matrix A. Requires A to be square and invertible.
print("\nInverse of A:\n", torch.inverse(A))



dot product v1·v2:
 tensor(32.)

A transpose (A.T):
 tensor([[3., 5., 4.],
        [6., 5., 3.],
        [1., 0., 8.]])

Inverse of A:
 tensor([[-0.3200,  0.3600,  0.0400],
        [ 0.3200, -0.1600, -0.0400],
        [ 0.0400, -0.1200,  0.1200]])


In [35]:

# ----- MATRIX DETERMINANT -----
# Computes the determinant of matrix A.
print("\ndet(A):\n", torch.det(A))


# ----- MATRIX TRACE (sum of diagonal) -----
# Computes the trace of matrix A, which is the sum of its diagonal elements.
print("\ntrace(A):\n", torch.trace(A))



det(A):
 tensor(-125.0000)

trace(A):
 tensor(16.)


In [36]:

# ----- MATRIX RANK -----
# Computes the rank of matrix A, which is the number of linearly independent rows or columns.
print("\nrank(A):\n", torch.linalg.matrix_rank(A))


# ----- MATRIX EIGENVALUES / EIGENVECTORS -----
# Computes the eigenvalues and eigenvectors of matrix A.
e_vals, e_vecs = torch.linalg.eig(A)
print("\neigenvalues:\n", e_vals)
print("eigenvectors:\n", e_vecs)


rank(A):
 tensor(3)

eigenvalues:
 tensor([-1.6753+0.j, 10.7064+0.j,  6.9689+0.j])
eigenvectors:
 tensor([[ 0.7921+0.j, -0.3588+0.j, -0.0863+0.j],
        [-0.5933+0.j, -0.3144+0.j, -0.2190+0.j],
        [-0.1435+0.j, -0.8789+0.j,  0.9719+0.j]])


In [37]:

# ----- MATRIX SVD (Singular Value Decomposition) -----
# Computes the Singular Value Decomposition of matrix A: A = U * diag(S) * Vh.
# U and Vh are unitary matrices, and S is a vector of singular values.
U, S, Vh = torch.linalg.svd(A)
print("\nSVD:")
print("U:\n", U)
print("S:\n", S)
print("Vh:\n", Vh)


SVD:
U:
 tensor([[-0.5097, -0.4325, -0.7437],
        [-0.5094, -0.5449,  0.6660],
        [-0.6933,  0.7184,  0.0574]])
S:
 tensor([11.9439,  6.2909,  1.6636])
Vh:
 tensor([[-0.5735, -0.6435, -0.5070],
        [-0.1825, -0.5030,  0.8448],
        [ 0.7986, -0.5770, -0.1710]])


### 5.Comparision Operations

In [38]:
x = torch.randint(0, 10, (3, 3)) # Create a 3x3 tensor with random integers (0-9).
y = torch.randint(0, 10, (3, 3)) # Create another 3x3 tensor with random integers (0-9).

print("x:\n", x)
print("y:\n", y)

# ----- ELEMENT-WISE COMPARISONS -----
print("\nx == y:\n", x == y)      # Check if elements are equal.
print("x != y:\n", x != y)        # Check if elements are not equal.
print("x > y:\n", x > y)          # Check if elements of x are greater than y.
print("x >= y:\n", x >= y)        # Check if elements of x are greater than or equal to y.
print("x < y:\n", x < y)          # Check if elements of x are less than y.
print("x <= y:\n", x <= y)        # Check if elements of x are less than or equal to y.

# ----- ANY / ALL LOGICAL REDUCTIONS -----
print("\nany(x > y):\n", torch.any(x > y))    # Check if any element of x is greater than y.
print("all(x > y):\n", torch.all(x > y))     # Check if all elements of x are greater than y.

x:
 tensor([[4, 7, 2],
        [3, 8, 5],
        [6, 2, 9]])
y:
 tensor([[5, 0, 4],
        [2, 7, 1],
        [1, 5, 4]])

x == y:
 tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
x != y:
 tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
x > y:
 tensor([[False,  True, False],
        [ True,  True,  True],
        [ True, False,  True]])
x >= y:
 tensor([[False,  True, False],
        [ True,  True,  True],
        [ True, False,  True]])
x < y:
 tensor([[ True, False,  True],
        [False, False, False],
        [False,  True, False]])
x <= y:
 tensor([[ True, False,  True],
        [False, False, False],
        [False,  True, False]])

any(x > y):
 tensor(True)
all(x > y):
 tensor(False)


### 6.Special Functions

In [39]:
import torch.nn.functional as F

# Create a tensor with random values.
x = torch.randn(3, 3)
print("x:\n", x)
# Sigmoid function: squashes values between 0 and 1.
print("\nsigmoid(x):\n", torch.sigmoid(x))

# Natural logarithm (avoid log(0) by adding a small epsilon).
print("\nlog(abs(x)+1e-6):\n", torch.log(torch.abs(x) + 1e-6))

# Exponential function: e^x.
print("\nexp(x):\n", torch.exp(x))

# Tanh function: squashes values between -1 and 1.
print("\ntanh(x):\n", torch.tanh(x))

# ReLU (Rectified Linear Unit) function: max(0, x).
print("\nReLU(x):\n", torch.relu(x))

# Softplus function: log(1 + exp(x)). A smooth approximation to ReLU.
print("\nsoftplus(x):\n", F.softplus(x))

# GELU (Gaussian Error Linear Unit) function: an activation function commonly used in transformers.
print("\nGELU(x):\n", F.gelu(x))

# Square root (use absolute value to avoid NaN for negative inputs).
print("\nsqrt(abs(x)):\n", torch.sqrt(torch.abs(x)))

# Natural logarithm (base e, use abs to avoid NaN for negative inputs).
print("\nlog(abs(x)):\n", torch.log(torch.abs(x)))

x:
 tensor([[-0.8216,  0.6133, -0.3497],
        [ 0.4890, -0.6925,  0.5929],
        [-0.0814,  0.1575, -0.3423]])

sigmoid(x):
 tensor([[0.3054, 0.6487, 0.4135],
        [0.6199, 0.3335, 0.6440],
        [0.4797, 0.5393, 0.4152]])

log(abs(x)+1e-6):
 tensor([[-0.1965, -0.4890, -1.0507],
        [-0.7154, -0.3674, -0.5227],
        [-2.5083, -1.8484, -1.0719]])

exp(x):
 tensor([[0.4397, 1.8464, 0.7049],
        [1.6307, 0.5003, 1.8092],
        [0.9218, 1.1706, 0.7101]])

tanh(x):
 tensor([[-0.6759,  0.5464, -0.3361],
        [ 0.4534, -0.5996,  0.5320],
        [-0.0812,  0.1562, -0.3296]])

ReLU(x):
 tensor([[0.0000, 0.6133, 0.0000],
        [0.4890, 0.0000, 0.5929],
        [0.0000, 0.1575, 0.0000]])

softplus(x):
 tensor([[0.3645, 1.0461, 0.5335],
        [0.9672, 0.4057, 1.0329],
        [0.6533, 0.7750, 0.5366]])

GELU(x):
 tensor([[-0.1690,  0.4478, -0.1270],
        [ 0.3362, -0.1692,  0.4289],
        [-0.0381,  0.0886, -0.1253]])

sqrt(abs(x)):
 tensor([[0.9064, 0.7831, 0.5

## Inplace operation

In [40]:
# Create a tensor.
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
print("Original x:\n", x)

# ----- INPLACE ADDITION -----
# Adds 1 to every element of x, modifying x directly.
x.add_(1)
print("\nx after x.add_(1):\n", x)

# ----- INPLACE SUBTRACTION -----
# Subtracts 2 from every element of x, modifying x directly.
x.sub_(2)
print("\nx after x.sub_(2):\n", x)

# ----- INPLACE MULTIPLICATION -----
# Multiplies every element of x by 3, modifying x directly.
x.mul_(3)
print("\nx after x.mul_(3):\n", x)

# ----- INPLACE DIVISION -----
# Divides every element of x by 2, modifying x directly.
x.div_(2)
print("\nx after x.div_(2):\n", x)

# ----- INPLACE RELU -----
# Create a new tensor for ReLU demonstration.
x = torch.tensor([-1.0, 0.0, 2.0, -3.0])
print("\nNew x for ReLU:\n", x)
# Applies ReLU function inplace: negative values become 0.
x.relu_()
print("\nx after x.relu_():\n", x)

# ----- INPLACE CLAMP -----
# Clamps values of x inplace between 0 and 2.
x.clamp_(min=0, max=2)
print("\nx after x.clamp_(0, 2):\n", x)

Original x:
 tensor([1., 2., 3., 4.])

x after x.add_(1):
 tensor([2., 3., 4., 5.])

x after x.sub_(2):
 tensor([0., 1., 2., 3.])

x after x.mul_(3):
 tensor([0., 3., 6., 9.])

x after x.div_(2):
 tensor([0.0000, 1.5000, 3.0000, 4.5000])

New x for ReLU:
 tensor([-1.,  0.,  2., -3.])

x after x.relu_():
 tensor([0., 0., 2., 0.])

x after x.clamp_(0, 2):
 tensor([0., 0., 2., 0.])


### Copy tensor

In [41]:
# Original tensor
x = torch.tensor([1.0, 2.0, 3.0])
print("Original x:\n", x)

# ----- 1. Using clone() -----
# Creates a new tensor with the same data as x, but it is a deep copy and does not share memory with x.
y = x.clone()
print("\ny (clone of x):\n", y)

# Modify y to show it's independent
y.add_(10) # Modifying y will not affect x.
print("Modified y:\n", y)
print("x remains unchanged:\n", x)

# ----- 2. Using detach().clone() (common with autograd) -----
# `detach()` removes the tensor from the computation graph, and then `clone()` creates a new copy.
z = x.detach().clone()
print("\nz (detached clone of x):\n", z)

# ----- 3. Using .copy_() to copy into an existing tensor -----
w = torch.zeros(3) # Create a target tensor.
w.copy_(x) # Copies the data from x into w inplace.
print("\nw after copy_ from x:\n", w)

Original x:
 tensor([1., 2., 3.])

y (clone of x):
 tensor([1., 2., 3.])
Modified y:
 tensor([11., 12., 13.])
x remains unchanged:
 tensor([1., 2., 3.])

z (detached clone of x):
 tensor([1., 2., 3.])

w after copy_ from x:
 tensor([1., 2., 3.])


In [42]:
# Get the memory address (ID) of tensor 'x'.
# This helps confirm if tensors share the same memory location.
id(x)

137346908995984

In [43]:
# Get the memory address (ID) of tensor 'y'.
# This should be different from id(x), confirming it's a separate copy.
id(y)

137351342230496

## Tensors on GPU


In [44]:
# Check if a CUDA-enabled GPU is available on the system.
# Returns True if CUDA is available, False otherwise.
torch.cuda.is_available()

True

In [45]:
# Define the device to use for tensor operations.
# If CUDA is available, 'cuda' device is chosen; otherwise, 'cpu' is used.
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [46]:
# Create a new tensor directly on the GPU device.
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [47]:
# Create a tensor on the CPU (default device).
a=torch.rand((2,3))

In [48]:
# Move an existing tensor 'a' from CPU to the specified 'device' (GPU if available).
# This operation returns a new tensor on the target device.
a.to(device)

tensor([[0.7340, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]], device='cuda:0')

In [49]:
import torch
import time

# Size of the matrices for performance comparison.
size = 10000  # Adjust if memory is limited.

# Create matrices on CPU.
A_cpu = torch.rand(size, size)
B_cpu = torch.rand(size, size)

# --- MATRIX MULTIPLICATION ON CPU --- (measures time for CPU computation)
start_cpu = time.time()
C_cpu = torch.matmul(A_cpu, B_cpu)
end_cpu = time.time()
print(f"CPU: Matrix multiplication of size {size}x{size} took {end_cpu - start_cpu:.4f} seconds.")

# --- MATRIX MULTIPLICATION ON GPU (if available) --- (measures time for GPU computation)
if torch.cuda.is_available():
    device = torch.device("cuda")
    A_gpu = A_cpu.to(device) # Move matrices to GPU.
    B_gpu = B_cpu.to(device)

    # Warm-up GPU: Perform a dummy operation to initialize GPU resources and get more accurate timing.
    _ = torch.matmul(A_gpu, B_gpu)

    torch.cuda.synchronize()  # Ensure all previous GPU operations have completed before starting timer.
    start_gpu = time.time()
    C_gpu = torch.matmul(A_gpu, B_gpu) # Perform matrix multiplication on GPU.
    torch.cuda.synchronize()  # Wait for GPU to finish its computation before ending timer.
    end_gpu = time.time()
    print(f"GPU: Matrix multiplication of size {size}x{size} took {end_gpu - start_gpu:.4f} seconds.")
else:
    print("GPU not available on this system.")

CPU: Matrix multiplication of size 10000x10000 took 29.5272 seconds.
GPU: Matrix multiplication of size 10000x10000 took 0.4720 seconds.


### Reshape tesnors


In [50]:
import torch

# Create a tensor of shape (2, 3, 4) with values from 0 to 23.
x = torch.arange(24).reshape(2, 3, 4)
print("Original x:\n", x)
print("Shape:", x.shape)

# ----- Reshape to (3, 8) -----
# Changes the tensor's shape to 3 rows and 8 columns. The total number of elements must remain the same.
y = x.reshape(3, 8)
print("\nReshaped to (3, 8):\n", y)
print("Shape:", y.shape)

# ----- Reshape using view (same as reshape for contiguous tensors) -----
# `view` can only operate on tensors that are contiguous in memory. `reshape` can handle non-contiguous tensors.
z = x.view(4, 6)
print("\nView to (4, 6):\n", z)
print("Shape:", z.shape)

# ----- Flatten to 1D tensor -----
# Converts the tensor into a 1D tensor containing all its elements.
flat = x.flatten()
print("\nFlattened x:\n", flat)
print("Shape:", flat.shape)

# ----- Permute dimensions (swap axes) -----
# Rearranges the dimensions of the tensor. For example, (2, 3, 4) becomes (4, 2, 3).
perm = x.permute(2, 0, 1)  # from (dim0, dim1, dim2) -> (dim2, dim0, dim1)
print("\nPermuted x (2,3,4 -> 4,2,3):\n", perm)
print("Shape:", perm.shape)

# ----- Unsqueeze (covered in next cell) -----


Original x:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Shape: torch.Size([2, 3, 4])

Reshaped to (3, 8):
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
Shape: torch.Size([3, 8])

View to (4, 6):
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
Shape: torch.Size([4, 6])

Flattened x:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
Shape: torch.Size([24])

Permuted x (2,3,4 -> 4,2,3):
 tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])
Shape: torch.Size([4, 2, 3])


In [51]:
import torch

# ----- Original tensor -----
x = torch.tensor([1, 2, 3, 4])
print("Original x:\n", x)
print("Shape:", x.shape)  # (4,)

# ----- UNSQUEEZE: Add a dimension -----
# Adds a new dimension of size 1 at the specified position.
x_unsq0 = x.unsqueeze(0)  # Add a dimension at index 0, making it (1, 4)
print("\nAfter unsqueeze(dim=0):\n", x_unsq0)
print("Shape:", x_unsq0.shape)  # (1, 4)

x_unsq1 = x.unsqueeze(1)  # Add a dimension at index 1, making it (4, 1)
print("\nAfter unsqueeze(dim=1):\n", x_unsq1)
print("Shape:", x_unsq1.shape)  # (4, 1)

# ----- SQUEEZE: Remove dimensions of size 1 -----
# Removes all dimensions of size 1 from the tensor.
x_squeezed0 = x_unsq0.squeeze()  # Removes the singleton dimension from (1, 4), resulting in (4,)
print("\nAfter squeeze():\n", x_squeezed0)
print("Shape:", x_squeezed0.shape)  # (4,)

x_squeezed1 = x_unsq1.squeeze()  # Removes the singleton dimension from (4, 1), resulting in (4,)
print("\nAfter squeeze() on x_unsq1:\n", x_squeezed1)
print("Shape:", x_squeezed1.shape)  # (4,)

# ----- EXAMPLE WITH 3D TENSOR -----
y = torch.randn(2, 1, 3) # Create a 3D tensor with a singleton dimension.
print("\nOriginal y:\n", y)
print("Shape:", y.shape)  # (2, 1, 3)

# Unsqueeze at dim=2
# Adds a dimension of size 1 at index 2, converting (2, 1, 3) to (2, 1, 1, 3).
y_unsq = y.unsqueeze(2)
print("\nAfter y.unsqueeze(2):\n", y_unsq)
print("Shape:", y_unsq.shape)  # (2, 1, 1, 3)

# Squeeze to remove all singleton dimensions
# Removes the singleton dimensions from (2, 1, 1, 3), resulting in (2, 3).
y_squeezed = y_unsq.squeeze()
print("\nAfter y_unsq.squeeze():\n", y_squeezed)
print("Shape:", y_squeezed.shape)  # (2, 3)

Original x:
 tensor([1, 2, 3, 4])
Shape: torch.Size([4])

After unsqueeze(dim=0):
 tensor([[1, 2, 3, 4]])
Shape: torch.Size([1, 4])

After unsqueeze(dim=1):
 tensor([[1],
        [2],
        [3],
        [4]])
Shape: torch.Size([4, 1])

After squeeze():
 tensor([1, 2, 3, 4])
Shape: torch.Size([4])

After squeeze() on x_unsq1:
 tensor([1, 2, 3, 4])
Shape: torch.Size([4])

Original y:
 tensor([[[ 2.1765, -0.0666, -0.8230]],

        [[ 0.2113, -0.8291,  0.7769]]])
Shape: torch.Size([2, 1, 3])

After y.unsqueeze(2):
 tensor([[[[ 2.1765, -0.0666, -0.8230]]],


        [[[ 0.2113, -0.8291,  0.7769]]]])
Shape: torch.Size([2, 1, 1, 3])

After y_unsq.squeeze():
 tensor([[ 2.1765, -0.0666, -0.8230],
        [ 0.2113, -0.8291,  0.7769]])
Shape: torch.Size([2, 3])


## Numpy and tesnors

In [52]:
import torch
import numpy as np

# ----- Create a PyTorch tensor -----
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("PyTorch tensor x:\n", x)
print("Type:", type(x))

# ----- Convert PyTorch tensor to NumPy array -----
# `numpy()` method converts a CPU tensor to a NumPy array.
x_np = x.numpy()
print("\nConverted to NumPy array:\n", x_np)
print("Type:", type(x_np))

# ----- Modify NumPy array and see effect on tensor -----
# IMPORTANT: When a CPU-based PyTorch tensor is converted to a NumPy array, they often share the same underlying memory.
# Modifying one will affect the other.
x_np[0, 0] = 100
print("\nModified NumPy array x_np:\n", x_np)
print("PyTorch tensor x after modifying NumPy array:\n", x)
# ✅ Note: They **share memory** if the tensor is on CPU.

# ----- Convert NumPy array back to PyTorch tensor -----
# `torch.from_numpy()` creates a PyTorch tensor from a NumPy array. This also shares memory.
y = torch.from_numpy(x_np)
print("\nConverted back to PyTorch tensor y:\n", y)
print("Type:", type(y))

# ----- Create tensor on GPU and convert to NumPy -----
if torch.cuda.is_available():
    x_gpu = x.to('cuda') # Move tensor x to GPU.
    # x_gpu.numpy() would give an error because NumPy cannot directly handle GPU tensors.
    x_cpu = x_gpu.cpu()  # First, move the GPU tensor back to CPU.
    x_np_gpu = x_cpu.numpy() # Then, convert the CPU tensor to a NumPy array.
    print("\nTensor on GPU moved to CPU and converted to NumPy:\n", x_np_gpu)

PyTorch tensor x:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Type: <class 'torch.Tensor'>

Converted to NumPy array:
 [[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>

Modified NumPy array x_np:
 [[100   2   3]
 [  4   5   6]]
PyTorch tensor x after modifying NumPy array:
 tensor([[100,   2,   3],
        [  4,   5,   6]])

Converted back to PyTorch tensor y:
 tensor([[100,   2,   3],
        [  4,   5,   6]])
Type: <class 'torch.Tensor'>

Tensor on GPU moved to CPU and converted to NumPy:
 [[100   2   3]
 [  4   5   6]]
